export const INSERT_COIN = 'INSERT COIN';
export const REPLENISH_STOCK = 'REPLENISH STOCK';
export const INPUT_SELECTION = 'INPUT SELECTION';
export const GIVE_CHANGE = 'GIVE CHANGE';
// export const TURN_ON_MACHINE = 'TURN ON MACHINE';